In [28]:
!pip install pandas numpy matplotlib seaborn scikit-learn

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (2.0.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.11/dist-packages (0.13.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (1.6.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (4.58.4)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (3.2.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [29]:
# import necessary python libraries
import pandas as pd
import numpy as np
# import machine learning libraries
from sklearn.multioutput import MultiOutputRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [30]:
# load the dataset
df = pd.read_csv('WaterPurity.csv', sep=';')
df

      id        date    NH4  BSK5  ...    NO2     SO4    PO4       CL
0      1  17.02.2000  0.330  2.77  ...  0.057  154.00  0.454   289.50
1      1  11.05.2000  0.044  3.00  ...  0.034  352.00  0.090  1792.00
2      1  11.09.2000  0.032  2.10  ...  0.173  416.00  0.200  2509.00
3      1  13.12.2000  0.170  2.23  ...  0.099  275.20  0.377  1264.00
4      1  02.03.2001  0.000  3.03  ...  0.065  281.60  0.134  1462.00
...   ..         ...    ...   ...  ...    ...     ...    ...      ...
2856  22  06.10.2020  0.046  2.69  ...  0.038  160.00  0.726    77.85
2857  22  27.10.2020  0.000  1.52  ...  0.031  147.20  0.634    71.95
2858  22  03.12.2020  0.034  0.29  ...  0.042  209.92  0.484    61.17
2859  22  12.01.2021  0.000  2.10  ...  0.034  121.60  0.424    63.49
2860  22  10.02.2021  0.000  1.78  ...  0.033  134.40  0.582    66.31

[2861 rows x 11 columns]

In [31]:
df.info() #data infomartion

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2861 entries, 0 to 2860
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         2861 non-null   int64
 1   date       2861 non-null   object
 2   NH4        2858 non-null   float64
 3   BSK5       2860 non-null   float64
 4   Suspended  2845 non-null   float64
 5   O2         2858 non-null   float64
 6   NO3        2860 non-null   float64
 7   NO2        2858 non-null   float64
 8   SO4        2812 non-null   float64
 9   PO4        2833 non-null   float64
 10  CL         2812 non-null   float64
dtypes: float64(9), int64(1), object(1)
memory usage: 246.0+ KB

In [32]:
df.shape # rows and columns

(2861, 11)

In [33]:
# Statistics of the data
df.describe().T # Here T is used for transposing rows to columns

            count       mean         std  ...     50%       75%       max
id         2861.0  12.397064    6.084226  ...  14.000  16.00000    22.000
NH4        2858.0   0.758734    2.486247  ...   0.220   0.50000    39.427
BSK5       2860.0   4.316182    2.973997  ...   3.800   5.80000    50.900
Suspended  2845.0  12.931905   16.543097  ...  10.000  15.00000   595.000
O2         2858.0   9.508902    4.428260  ...   8.995  11.52000    90.000
NO3        2860.0   4.316846    6.881188  ...   2.800   5.58250   133.400
NO2        2858.0   0.246128    2.182777  ...   0.059   0.12575   109.000
SO4        2812.0  59.362313   96.582641  ...  37.800  64.64000  3573.400
PO4        2833.0   0.418626    0.771326  ...   0.270   0.47000    13.879
CL         2812.0  93.731991  394.512184  ...  33.900  45.60750  5615.280

[10 rows x 8 columns]

In [34]:
# Missing values in the dataset
df.isnull().sum()

id            0
date          0
NH4           3
BSK5          1
Suspended    16
O2            3
NO3           1
NO2           3
SO4          49
PO4          28
CL           49
dtype: int64

In [35]:
# data is in object-date format
df['date'] = pd.to_datetime(df['date'], format='%d.%m.%Y')
df

      id       date    NH4  BSK5  ...    NO2     SO4    PO4       CL
0      1 2000-02-17  0.330  2.77  ...  0.057  154.00  0.454   289.50
1      1 2000-05-11  0.044  3.00  ...  0.034  352.00  0.090  1792.00
2      1 2000-09-11  0.032  2.10  ...  0.173  416.00  0.200  2509.00
3      1 2000-12-13  0.170  2.23  ...  0.099  275.20  0.377  1264.00
4      1 2001-03-02  0.000  3.03  ...  0.065  281.60  0.134  1462.00
...   ..        ...    ...   ...  ...    ...     ...    ...      ...
2856  22 2020-10-06  0.046  2.69  ...  0.038  160.00  0.726    77.85
2857  22 2020-10-27  0.000  1.52  ...  0.031  147.20  0.634    71.95
2858  22 2020-12-03  0.034  0.29  ...  0.042  209.92  0.484    61.17
2859  22 2021-01-12  0.000  2.10  ...  0.034  121.60  0.424    63.49
2860  22 2021-02-10  0.000  1.78  ...  0.033  134.40  0.582    66.31

[2861 rows x 11 columns]

In [36]:
df.info() # gives information of the current dataset after the updation

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2861 entries, 0 to 2860
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         2861 non-null   int64
 1   date       2861 non-null   datetime64[ns]
 2   NH4        2858 non-null   float64
 3   BSK5       2860 non-null   float64
 4   Suspended  2845 non-null   float64
 5   O2         2858 non-null   float64
 6   NO3        2860 non-null   float64
 7   NO2        2858 non-null   float64
 8   SO4        2812 non-null   float64
 9   PO4        2833 non-null   float64
 10  CL         2812 non-null   float64
dtypes: datetime64[ns](1), float64(9), int64(1)
memory usage: 246.0 KB

In [37]:
df = df.sort_values(by=['id','date']) # sorts data according to the formart
df.head(10) # Used to give print the initial selected data

   id       date    NH4  BSK5  Suspended  ...     NO3    NO2    SO4    PO4      CL
0   1 2000-02-17  0.330  2.77       12.0  ...   9.500  0.057  154.0  0.454   289.5
1   1 2000-05-11  0.044  3.00       51.6  ...  17.750  0.034  352.0  0.090  1792.0
2   1 2000-09-11  0.032  2.10       24.5  ...  13.800  0.173  416.0  0.200  2509.0
3   1 2000-12-13  0.170  2.23       35.6  ...  17.130  0.099  275.2  0.377  1264.0
4   1 2001-03-02  0.000  3.03       48.8  ...  10.000  0.065  281.6  0.134  1462.0
5   1 2001-06-07  0.020  4.02       34.0  ...  11.800  0.016  287.0  0.208  1183.0
6   1 2001-09-10  0.863  3.91      147.0  ...  20.500  0.284  595.2  0.674  4023.0
7   1 2001-11-06  0.060  2.97       71.2  ...  25.800  0.095  314.0  0.390  1907.0
8   1 2002-03-12  0.168  4.15       27.0  ...   3.945  0.058  153.6  0.110   473.0
9   1 2002-06-06  0.001  7.11       74.4  ...   2.260  0.017  409.6  0.181  1782.0

[10 rows x 11 columns]

In [38]:
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day
df

      id       date    NH4  BSK5  Suspended  ...    PO4       CL  year  month  day
0      1 2000-02-17  0.330  2.77       12.0  ...  0.454   289.50  2000      2   17
1      1 2000-05-11  0.044  3.00       51.6  ...  0.090  1792.00  2000      5   11
2      1 2000-09-11  0.032  2.10       24.5  ...  0.200  2509.00  2000      9   11
3      1 2000-12-13  0.170  2.23       35.6  ...  0.377  1264.00  2000     12   13
4      1 2001-03-02  0.000  3.03       48.8  ...  0.134  1462.00  2001      3    2
...   ..        ...    ...   ...        ...  ...    ...      ...   ...    ...  ...
2856  22 2020-10-06  0.046  2.69        3.6  ...  0.726    77.85  2020     10    6
2857  22 2020-10-27  0.000  1.52        0.5  ...  0.634    71.95  2020     10   27
2858  22 2020-12-03  0.034  0.29        0.8  ...  0.484    61.17  2020     12    3
2859  22 2021-01-12  0.000  2.10        0.0  ...  0.424    63.49  2021      1   12
2860  22 2021-02-10  0.000  1.78        0.0  ...  0.582    66.31  2021      2   10

[2861 rows x 14 columns]

In [39]:
df.columns

Index(['id', 'date', 'NH4', 'BSK5', 'Suspended', 'O2', 'NO3', 'NO2', 'SO4',
       'PO4', 'CL', 'year', 'month', 'day'],
      dtype='object')

In [40]:
Pollutants = ['O2', 'NO3', 'NO2', 'SO4',
       'PO4', 'CL']